version: '3.0'
services:
  backend:
    build: ./backend
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./samples/:/app/samples/
    networks:
        internal:
            aliases:
              - backend
  frontend:
    build: ./frontend
    environment:
      - PORT=80
    links:
      - backend
    networks:
      internal:
        aliases:
          - frontend
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./database/:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: tijolo22
    networks:
      internal:
        aliases:
          - database
  proxy:
    image: nginx
    depends_on:
      - frontend
      - backend
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # For production only
      - ./fullchain.pem:/etc/letsencrypt/fullchain.pem
      - ./privkey.pem:/etc/letsencrypt/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      internal:
        aliases:
          - proxy

networks:
  internal: