services:
  backend:
    build: ./backend
    ports:
      - "81:80"
    links:
      - database
    volumes:
      - ./samples/:/app/samples/
  frontend:
    build: ./frontend
    environment:
      - PORT=80
    ports:
      - "80:80"
    links:
      - backend
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./database/:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: tijolo22